routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/empresa', 'EmpresaController@index')->name('empresa');

Route::resource('temperaturas', 'TemperaturaController');

Route::resource('recargas', 'RecargaController');

Route::resource('condominios', 'CondominioController');

Route::resource('estanques', 'EstanqueController');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'GestionCombustible') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'GestionCombustible') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Ingresar</a></li>
                            <li><a href="{{ route('register') }}">Registro</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Salir
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

		<div class="container-fluid">
			<div class="row">
				<div class="col-md-12">
					<div class="row">
						<div class="col-md-2">
							<div class="panel panel-default">
								<div class="panel-body">
									<a href={!! route('home') !!}>
                                        <i class="fa fa-map-marker" aria-hidden="true"></i>
                                        Mapa
                                    </a>
								</div>
                                <div class="panel-body">
									<a href={!! route('condominios.index') !!}>
                                        <i class="fa fa-home" aria-hidden="true"></i>
                                        Condominios
                                    </a>
								</div>
                                <div class="panel-body">
									<a href={!! route('estanques.index') !!}>
                                        <i class="fa fa-truck" aria-hidden="true"></i>
                                        Estanques
                                    </a>
								</div>
								<div class="panel-body">
									<a href={!! route('recargas.index') !!}>
                                        <i class="fa fa-battery-half" aria-hidden="true"></i>
                                        Recargas
                                    </a>
								</div>
								<div class="panel-body">
									<a href={!! route('temperaturas.index') !!}>
                                        <i class="fa fa-thermometer-empty" aria-hidden="true"></i>
                                        Temperatura
                                    </a>
								</div>
								
                                <!--
								<div class="panel-body">
									<a href={!! route('home') !!}>Detalle condominios</a>
								</div>
                                -->
								<div class="panel-body">
									<a href={!! route('empresa') !!}>
                                        <i class="fa fa-building" aria-hidden="true"></i>
                                        Acerca
                                    </a>
								</div>
							</div>
						</div>
						<div class="col-md-10">
							<div class="jumbotron">
								 @yield('content')
							</div>
						</div>
					</div>
				</div>
			</div>
</div>
		
       
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>